[workspace]
resolver="2"
members = [
    "node",
    "pallets/dex",
    "pallets/voting",
    "pallets/dpos",
    "pallets/multisig",
    "pallets/treasury",
    "pallets/free-tx",
    "runtime",
]
[profile.release]
panic = "unwind"
